Parameters:  ##변수 선언
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:  ##리소스는 필수 항목
  MyInstance:  ##Local ID로 아래 리소스를 식별한다. 따라서 밑에서는 MYInstance(local ID)와 겹치면 안된다.
    Type: AWS::EC2::Instance  ##매개변수 - Instance 생성관련 
    Properties:
      ImageId: ami-084e92d3e117f7692  ##AMI 카탈로그에서 이미지 ID 
      InstanceType: t2.micro  ## 인스턴스 타입 지정
      KeyName: !Ref KeyName  ## !Ref(참조하다) 위에 Parameters에 있는 KeyName을 사용한다. 그냥 키 페어에서 있는 이름을 넣어도 무방하다.
      Tags:  ## EC2 Instance 이름 지정
        - Key: Name
          Value: MyInstance
      SecurityGroups:  ## 보안 그룹 지정
        - !Ref MySG
      UserData:
        Fn::Base64:  ## 만들어지고 사용되는 내용
          !Sub |
            #!/bin/bash
            yum install httpd -y
            systemctl start httpd
            echo "<h1>Test Web Server</h1>" > /var/www/html/index.html

  MySG:  ##local ID
    Type: AWS::EC2::SecurityGroup  ## 보안 그룹 생성
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
        

